openapi: 3.0.0
info:
  title: Node.js Backend API
  description: API documentation for the Node.js backend handling contacts.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /contacts:
    get:
      summary: Get all contacts
      responses:
        '200':
          description: A list of contacts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
        '500':
          description: Internal Server Error
    post:
      summary: Create a new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactInput'
      responses:
        '201':
          description: Contact added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  contactID:
                    type: integer
        '500':
          description: Internal Server Error

  /contacts/{id}:
    get:
      summary: Get contact by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the contact to retrieve
      responses:
        '200':
          description: A contact object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        '404':
          description: Contact not found
        '500':
          description: Internal Server Error
    put:
      summary: Update a contact by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the contact to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactInput'
      responses:
        '200':
          description: Contact updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Contact not found
        '500':
          description: Internal Server Error

components:
  schemas:
    Contact:
      type: object
      properties:
        ContactID:
          type: integer
        FirstName:
          type: string
        LastName:
          type: string
        OfficialEmailAddress:
          type: string
        PersonalEmailAddress:
          type: string
        OfficialPhoneNumber:
          type: string
        PersonalPhoneNumber:
          type: string
        Role:
          type: string
        AssociatedAccount:
          type: integer
        ContactChannel:
          type: string
        IsActive:
          type: boolean
        LastContactDate:
          type: string
          format: date
        PreferredLanguage:
          type: string
        DoNotContact:
          type: boolean
        RecordCreatedBy:
          type: integer
        RecordLastModifiedBy:
          type: integer
        CreatedTimestamp:
          type: string
          format: date-time
        ModifiedTimestamp:
          type: string
          format: date-time
        ExternalSystemID:
          type: string
        Notes:
          type: string

    ContactInput:
      type: object
      properties:
        FirstName:
          type: string
        LastName:
          type: string
        OfficialEmailAddress:
          type: string
        PersonalEmailAddress:
          type: string
        OfficialPhoneNumber:
          type: string
        PersonalPhoneNumber:
          type: string
        Role:
          type: string
        AssociatedAccount:
          type: integer
        ContactChannel:
          type: string
        IsActive:
          type: boolean
        LastContactDate:
          type: string
          format: date
        PreferredLanguage:
          type: string
        DoNotContact:
          type: boolean
        RecordCreatedBy:
          type: integer
        RecordLastModifiedBy:
          type: integer
        ExternalSystemID:
          type: string
        Notes:
          type: string
